services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/redis:/data
    environment:
      - REDIS_PASSWORD=persistencia
    command: ["redis-server", "--requirepass", "persistencia"]
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: persistencia
      MYSQL_DATABASE: persistencia
      MYSQL_USER: persistencia
      MYSQL_PASSWORD: persistencia
    ports:
      - "3306:3306"
    volumes:
      - ./db-data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
